name: Solar System Workflow
env:
   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
   MONGO_URI: ${{ vars.MONGO_URI }}
   MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: setup NodeJS of version 18
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install NodeJS dependencies
          run: npm install
        
        - name:  Run Code-coverage command
          - continue-on-error: truecontinue-on-error: true
          run: npm run code-coverage

        - name: Upload code-coverage reports
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5              

